"""
CarHunter v3.0 — Cross-Source Duplicate Detection
==================================================
Detects likely duplicate vehicle listings that appear on more than one
source (e.g. AutoScout24 and PKW.de) without performing any automatic
vehicle merge.

SAFETY CONTRACT
---------------
* Detection is read-only with respect to listings, vehicles,
  source_listings, source_snapshots, and the cars compatibility table.
* The only writes are to listing_duplicate_candidates.
* No Vehicle.vehicle_id is ever modified.
* No Listing is ever deleted or merged.
* VIN-based automatic resolution remains the sole auto-merge path
  (implemented separately in database.resolve_canonical_vehicle_links).

DESIGN
------
1. Blocking
   Candidate pairs are generated by matching on tight price + mileage
   bands (≤3 % price difference, ≤5 % + 1 000 km mileage difference)
   across listings from DIFFERENT sources.  Only ACTIVE listings are
   considered.

2. Scoring
   Each candidate pair is scored using explicit deterministic signals:

   VERY_STRONG  (≥85): only reachable with multiple strong signals
   STRONG       (≥60): consistent key fields
   POSSIBLE     (≥35): some overlapping fields
   LOW          (<35):  weak coincidence

3. Persistence
   Results are stored in listing_duplicate_candidates with stable
   pair ordering (min_id, max_id) to guarantee idempotency.
   Operator decisions (CONFIRMED_SAME / CONFIRMED_DIFFERENT / DISMISSED)
   are preserved on rescore.
"""

from __future__ import annotations

import json
import re
import unicodedata
from datetime import datetime
from typing import Any

import database


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------

_DDL = """
CREATE TABLE IF NOT EXISTS listing_duplicate_candidates (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    listing_id_a      INTEGER NOT NULL,
    listing_id_b      INTEGER NOT NULL,
    score             INTEGER NOT NULL,
    classification    TEXT NOT NULL,
    evidence          TEXT NOT NULL DEFAULT '[]',
    differences       TEXT NOT NULL DEFAULT '[]',
    status            TEXT NOT NULL DEFAULT 'OPEN',
    last_evaluated_at TEXT,
    created_at        TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(listing_id_a, listing_id_b),
    FOREIGN KEY (listing_id_a) REFERENCES listings(id),
    FOREIGN KEY (listing_id_b) REFERENCES listings(id),
    CHECK (listing_id_a < listing_id_b),
    CHECK (status IN ('OPEN','CONFIRMED_SAME','CONFIRMED_DIFFERENT','DISMISSED','STALE'))
);
CREATE INDEX IF NOT EXISTS idx_ldc_status
    ON listing_duplicate_candidates(status);
CREATE INDEX IF NOT EXISTS idx_ldc_classification
    ON listing_duplicate_candidates(classification, score DESC);
"""

# ---------------------------------------------------------------------------
# Scoring weights
# ---------------------------------------------------------------------------

_W_PRICE_EXACT    = 20   # price within 1%
_W_MILEAGE_EXACT  = 20   # mileage within 2% or 500 km
_W_SELLER_MATCH   = 20   # normalised dealer name match
_W_REG_YEAR       = 10   # same registration year
_W_TITLE_HIGH     = 10   # normalised title similarity ≥ 0.85
_W_TITLE_MOD      =  5   # normalised title similarity ≥ 0.60
_W_DESC_HIGH      =  8   # long shared description tokens ≥ 0.70
_W_POWER_MATCH    =  5   # same power (hp) within 5%
_W_TRANSMISSION   =  3   # same gearbox family
_W_DRIVETRAIN     =  3   # same drive type
_W_COLOUR_MATCH   =  2   # same colour family

_PENALTY_VIN_CONFLICT   = -80   # conflicting VINs → never strong
_PENALTY_REG_MISMATCH   = -15   # different reg year
_PENALTY_POWER_CONFLICT = -10   # clearly different engine (>15% difference)
_PENALTY_SELLER_NEG     =  -8   # explicitly different seller (when both known)

_CLASSIFICATION_VERY_STRONG = "VERY_STRONG"
_CLASSIFICATION_STRONG      = "STRONG"
_CLASSIFICATION_POSSIBLE    = "POSSIBLE"
_CLASSIFICATION_LOW         = "LOW"


# ---------------------------------------------------------------------------
# Normalisation helpers
# ---------------------------------------------------------------------------

def _norm_text(s: str | None) -> str:
    if not s:
        return ""
    s = unicodedata.normalize("NFC", str(s))
    s = s.upper()
    s = re.sub(r"[^\w\s]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


_LEGAL_SUFFIXES = re.compile(
    r"\b(GMBH|CO|KG|AG|GBMR|MBHG|UND|&|E\.K\.|EK|SARL|SAS|SRL|BV)\b",
    re.IGNORECASE,
)

def _norm_seller(s: str | None) -> str:
    if not s:
        return ""
    # Extract companyName from Python dict repr or JSON string
    # e.g. "{'companyName': 'Autocenter Neuss ...'}"
    cn_match = re.search(r"['\"]?companyName['\"]?\s*[:=]\s*['\"]([^'\"]+)['\"]", s)
    if cn_match:
        s = cn_match.group(1)
    s = _norm_text(s)
    s = _LEGAL_SUFFIXES.sub(" ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


_COLOUR_MAP = {
    "grau": "grey", "gray": "grey", "grey": "grey", "grijs": "grey",
    "silbergrau": "grey",
    "weiss": "white", "white": "white", "weiß": "white", "wit": "white",
    "schwarz": "black", "black": "black", "zwart": "black",
    "silber": "silver", "silver": "silver", "zilver": "silver",
    "blau": "blue", "blue": "blue", "blauw": "blue",
    "rot": "red", "red": "red", "rood": "red",
    "grün": "green", "green": "green", "groen": "green",
    "braun": "brown", "brown": "brown", "bruin": "brown",
    "beige": "beige",
    "orange": "orange", "oranje": "orange",
    "gelb": "yellow", "yellow": "yellow", "geel": "yellow",
    "violett": "purple", "purple": "purple", "paars": "purple",
}

def _norm_colour(s: str | None) -> str:
    if not s:
        return ""
    key = s.lower().strip()
    return _COLOUR_MAP.get(key, key)


_DRIVE_MAP = {
    "allrad": "awd", "4wd": "awd", "awd": "awd", "quattro": "awd",
    "4x4": "awd", "4motion": "awd",
    "front": "fwd", "fwd": "fwd", "frontantrieb": "fwd",
    "rear": "rwd", "rwd": "rwd", "hinterrad": "rwd",
}

def _norm_drive(s: str | None) -> str:
    if not s:
        return ""
    return _DRIVE_MAP.get(s.lower().strip(), s.lower().strip())


_GEARBOX_MAP = {
    "automatik": "auto", "automatic": "auto", "auto": "auto",
    "dsg": "auto", "s tronic": "auto", "s-tronic": "auto",
    "tiptronic": "auto", "pdk": "auto", "cvt": "auto",
    "schaltgetriebe": "manual", "manual": "manual", "manuell": "manual",
}

def _norm_gearbox(s: str | None) -> str:
    if not s:
        return ""
    return _GEARBOX_MAP.get(s.lower().strip(), s.lower().strip())


def _token_similarity(a: str, b: str) -> float:
    """Jaccard similarity on word tokens."""
    if not a or not b:
        return 0.0
    ta = set(_norm_text(a).split())
    tb = set(_norm_text(b).split())
    if not ta or not tb:
        return 0.0
    intersection = ta & tb
    union = ta | tb
    return len(intersection) / len(union)


def _long_common_tokens(a: str, b: str) -> float:
    """Token overlap on words ≥5 chars — filters out common stop words."""
    if not a or not b:
        return 0.0
    ta = {w for w in _norm_text(a).split() if len(w) >= 5}
    tb = {w for w in _norm_text(b).split() if len(w) >= 5}
    if not ta or not tb:
        return 0.0
    return len(ta & tb) / max(len(ta), len(tb))


# ---------------------------------------------------------------------------
# Snapshot field extractor
# ---------------------------------------------------------------------------

def _get_snapshot_fields(listing_id: int, conn) -> dict[str, Any]:
    """
    Return merged extracted_fields for a listing, combining all snapshots
    so that detail fields present in an older snapshot are not lost if the
    latest snapshot is a summary-only re-scrape.
    Earlier snapshots are applied first (lowest precedence); later snapshots
    override, but only for non-empty values.
    """
    rows = conn.execute(
        """
        SELECT ss.extracted_fields
        FROM source_snapshots ss
        JOIN source_listings sl
          ON sl.source_id = ss.source_id
         AND sl.source_listing_id = ss.source_listing_id
        JOIN listings l ON l.source_listing_row_id = sl.id
        WHERE l.id = ?
        ORDER BY ss.id ASC
        """,
        (listing_id,),
    ).fetchall()
    merged: dict[str, Any] = {}
    for row in rows:
        if row and row[0]:
            try:
                fields = json.loads(row[0])
                for k, v in fields.items():
                    if v is not None and v != "" and v != [] and v != {}:
                        merged[k] = v
            except (ValueError, TypeError):
                pass
    return merged


def _listing_data(listing_row, snap: dict[str, Any]) -> dict[str, Any]:
    """
    Build the data dict used for scoring.

    TEMPORAL SAFETY RULE:
    Mutable fields that reflect current market state — price, mileage,
    seller — are taken EXCLUSIVELY from the listings table columns
    (current_price, current_mileage, current_seller).  Snapshot fields
    are never allowed to override these even if the snapshot is richer,
    because an older snapshot may reflect a different price/mileage/owner.

    Stable descriptive fields — title, year, colour, power, drivetrain,
    transmission, VIN, make, model, first_registration — may be enriched
    from historical snapshots because they do not change meaningfully
    across a vehicle's listing lifetime.
    """
    lid, source_id, source_listing_id, price, mileage, seller, description, options = listing_row

    # Prefer description; fall back to options JSON as comparable text
    desc_text = description or snap.get("description")
    if not desc_text and options:
        try:
            opts = json.loads(options) if isinstance(options, str) else options
            if isinstance(opts, list):
                desc_text = " ".join(str(o) for o in opts)
        except (ValueError, TypeError):
            desc_text = str(options)

    return {
        "id": lid,
        "source_id": source_id,
        "source_listing_id": source_listing_id,
        # ── MUTABLE (current state from listings table only) ───────────────
        "price": price,          # current_price — never from snapshot
        "mileage": mileage,      # current_mileage — never from snapshot
        "seller": seller,        # current_seller — never from snapshot
        # ── STABLE DESCRIPTIVE (snapshot enrichment allowed) ──────────────
        "description": desc_text,
        "options": options,
        "title": snap.get("title"),
        "year": snap.get("year"),
        "first_registration": snap.get("first_registration"),
        "colour": snap.get("colour") or snap.get("color"),
        "power_hp": snap.get("power_hp") or snap.get("hp"),
        "drivetrain": snap.get("drivetrain") or snap.get("drive"),
        "transmission": snap.get("transmission") or snap.get("gearbox"),
        "vin": snap.get("vin"),
        "make": snap.get("make"),
        "model": snap.get("model"),
    }


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------

def score_pair(a: dict[str, Any], b: dict[str, Any]) -> dict[str, Any]:
    """
    Score a candidate pair and return a result dict with:
      score, classification, reasons (evidence), differences

    VIN VETO: conflicting VINs are an absolute veto for STRONG/VERY_STRONG
    regardless of all other signals.  The classification is capped at POSSIBLE
    and the score is zeroed when VINs conflict.
    """
    score = 0
    reasons: list[str] = []
    differences: list[str] = []
    vin_conflict = False

    # ── VIN check ──────────────────────────────────────────────────────────
    vin_a = (a.get("vin") or "").strip().upper()
    vin_b = (b.get("vin") or "").strip().upper()
    if vin_a and vin_b:
        if vin_a == vin_b:
            # VIN match is handled by ARCH-007 auto-merge; record as evidence.
            reasons.append("exact VIN match")
            score += 40
        else:
            vin_conflict = True
            differences.append(f"conflicting VIN: {vin_a} vs {vin_b}")

    # ── Price ───────────────────────────────────────────────────────────────
    pa, pb = a.get("price"), b.get("price")
    if pa and pb:
        diff_pct = abs(pa - pb) / max(pa, pb)
        if diff_pct <= 0.01:
            score += _W_PRICE_EXACT
            reasons.append(f"exact price: {pa}")
        elif diff_pct <= 0.05:
            score += _W_PRICE_EXACT // 2
            reasons.append(f"very close price: {pa} vs {pb}")
        else:
            differences.append(f"price difference: {pa} vs {pb} ({diff_pct:.0%})")

    # ── Mileage ─────────────────────────────────────────────────────────────
    ma = a.get("mileage")
    mb = b.get("mileage")
    if ma and mb:
        diff_km = abs(ma - mb)
        diff_pct = diff_km / max(ma, mb)
        if diff_km <= 500 or diff_pct <= 0.02:
            score += _W_MILEAGE_EXACT
            reasons.append(f"exact mileage: {ma} km")
        elif diff_pct <= 0.05:
            score += _W_MILEAGE_EXACT // 2
            reasons.append(f"close mileage: {ma} vs {mb} km")
        else:
            differences.append(f"mileage difference: {ma} vs {mb} km ({diff_pct:.0%})")

    # ── Seller ──────────────────────────────────────────────────────────────
    sa = _norm_seller(a.get("seller"))
    sb = _norm_seller(b.get("seller"))
    if sa and sb:
        sim = _token_similarity(sa, sb)
        if sim >= 0.70:
            score += _W_SELLER_MATCH
            reasons.append(f"same seller: {a.get('seller')!r}")
        elif sim >= 0.40:
            score += _W_SELLER_MATCH // 2
            reasons.append("similar seller name")
        else:
            score += _PENALTY_SELLER_NEG
            differences.append(f"different seller: {a.get('seller')!r} vs {b.get('seller')!r}")

    # ── Registration year ───────────────────────────────────────────────────
    ya = _reg_year(a)
    yb = _reg_year(b)
    if ya and yb:
        if ya == yb:
            score += _W_REG_YEAR
            reasons.append(f"same registration year: {ya}")
        else:
            score += _PENALTY_REG_MISMATCH
            differences.append(f"different year: {ya} vs {yb}")

    # ── Title similarity ────────────────────────────────────────────────────
    ta, tb = a.get("title"), b.get("title")
    if ta and tb:
        # Use token-overlap but also reward when the shorter title's tokens
        # are a subset of the longer title (abbreviated form).
        ta_norm = set(_norm_text(ta).split())
        tb_norm = set(_norm_text(tb).split())
        shorter, longer = (ta_norm, tb_norm) if len(ta_norm) <= len(tb_norm) else (tb_norm, ta_norm)
        containment = len(shorter & longer) / len(shorter) if shorter else 0.0
        jaccard = len(ta_norm & tb_norm) / len(ta_norm | tb_norm) if (ta_norm | tb_norm) else 0.0
        sim = max(containment, jaccard)
        if sim >= 0.85:
            score += _W_TITLE_HIGH
            reasons.append(f"high title similarity ({sim:.0%}): {ta!r}")
        elif sim >= 0.60:
            score += _W_TITLE_MOD
            reasons.append(f"moderate title similarity ({sim:.0%})")
        else:
            differences.append(f"low title similarity ({sim:.0%}): {ta!r} vs {tb!r}")

    # ── Description overlap ─────────────────────────────────────────────────
    da, db = a.get("description"), b.get("description")
    if da and db and len(da) > 100 and len(db) > 100:
        sim = _long_common_tokens(da, db)
        if sim >= 0.70:
            score += _W_DESC_HIGH
            reasons.append(f"high description/equipment overlap ({sim:.0%})")
        elif sim >= 0.40:
            score += _W_DESC_HIGH // 2
            reasons.append(f"moderate description overlap ({sim:.0%})")

    # ── Power ───────────────────────────────────────────────────────────────
    hpa = _to_int(a.get("power_hp"))
    hpb = _to_int(b.get("power_hp"))
    if hpa and hpb:
        diff_pct = abs(hpa - hpb) / max(hpa, hpb)
        if diff_pct <= 0.05:
            score += _W_POWER_MATCH
            reasons.append(f"same power: {hpa} hp")
        elif diff_pct > 0.15:
            score += _PENALTY_POWER_CONFLICT
            differences.append(f"different power: {hpa} vs {hpb} hp")

    # ── Transmission ────────────────────────────────────────────────────────
    ga = _norm_gearbox(a.get("transmission"))
    gb = _norm_gearbox(b.get("transmission"))
    if ga and gb:
        if ga == gb:
            score += _W_TRANSMISSION
            reasons.append(f"same transmission: {ga}")
        else:
            differences.append(f"different transmission: {ga} vs {gb}")

    # ── Drivetrain ──────────────────────────────────────────────────────────
    dra = _norm_drive(a.get("drivetrain"))
    drb = _norm_drive(b.get("drivetrain"))
    if dra and drb:
        if dra == drb:
            score += _W_DRIVETRAIN
            reasons.append(f"same drivetrain: {dra}")
        else:
            differences.append(f"different drivetrain: {dra} vs {drb}")

    # ── Colour ──────────────────────────────────────────────────────────────
    ca = _norm_colour(a.get("colour"))
    cb = _norm_colour(b.get("colour"))
    if ca and cb:
        if ca == cb:
            score += _W_COLOUR_MATCH
            reasons.append(f"same colour: {ca}")
        else:
            differences.append(f"different colour: {ca} vs {cb}")

    score = max(0, min(100, score))

    # ── VIN conflict hard veto ──────────────────────────────────────────────
    # Conflicting VINs mean these cannot be the same physical vehicle.
    # Cap classification at POSSIBLE and zero the score, regardless of
    # how many other signals matched.
    if vin_conflict:
        score = min(score, 30)
        classification = _CLASSIFICATION_POSSIBLE if score >= 35 else _CLASSIFICATION_LOW
        differences.insert(0, "VIN_CONFLICT_VETO: capped at POSSIBLE")
    else:
        classification = _classify(score)

    return {
        "score": score,
        "classification": classification,
        "reasons": reasons,
        "differences": differences,
    }


def _reg_year(d: dict) -> int | None:
    yr = d.get("year")
    if yr:
        try:
            return int(str(yr)[:4])
        except (ValueError, TypeError):
            pass
    reg = d.get("first_registration") or ""
    m = re.match(r"(\d{4})", str(reg))
    if m:
        return int(m.group(1))
    return None


def _to_int(v) -> int | None:
    try:
        return int(v) if v is not None else None
    except (ValueError, TypeError):
        return None


def _classify(score: int) -> str:
    if score >= 85:
        return _CLASSIFICATION_VERY_STRONG
    if score >= 60:
        return _CLASSIFICATION_STRONG
    if score >= 35:
        return _CLASSIFICATION_POSSIBLE
    return _CLASSIFICATION_LOW


# ---------------------------------------------------------------------------
# Candidate generation
# ---------------------------------------------------------------------------

_CANDIDATE_QUERY = """
SELECT
    a.id, a.source_id, a.source_listing_id, a.current_price, a.current_mileage,
    a.current_seller, a.current_description, a.current_options,
    b.id, b.source_id, b.source_listing_id, b.current_price, b.current_mileage,
    b.current_seller, b.current_description, b.current_options
FROM listings a
JOIN listings b ON b.id > a.id
WHERE a.source_id != b.source_id
  AND a.availability = 'ACTIVE'
  AND b.availability = 'ACTIVE'
  AND a.current_price IS NOT NULL
  AND b.current_price IS NOT NULL
  AND ABS(CAST(a.current_price AS REAL) - CAST(b.current_price AS REAL))
      <= (a.current_price * 0.03 + 200)
  AND (
    a.current_mileage IS NULL
    OR b.current_mileage IS NULL
    OR ABS(CAST(a.current_mileage AS REAL) - CAST(b.current_mileage AS REAL))
       <= (a.current_mileage * 0.05 + 1000)
  )
"""


def generate_candidates(conn) -> list[tuple[dict, dict]]:
    """
    Return (listing_a_data, listing_b_data) pairs from different sources
    that pass the price + mileage blocking filter.
    """
    rows = conn.execute(_CANDIDATE_QUERY).fetchall()
    pairs = []
    for row in rows:
        a_row = row[:8]
        b_row = row[8:]
        snap_a = _get_snapshot_fields(a_row[0], conn)
        snap_b = _get_snapshot_fields(b_row[0], conn)
        pairs.append((_listing_data(a_row, snap_a), _listing_data(b_row, snap_b)))
    return pairs


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------

def ensure_schema(conn) -> None:
    """Create detection tables and indexes if they do not exist.

    Does NOT commit; the caller controls the transaction.  When called
    from run_detection with an internally-owned connection the commit
    happens naturally; when called with an external connection the caller
    remains in control.
    """
    for stmt in _DDL.strip().split(";"):
        stmt = stmt.strip()
        if stmt:
            conn.execute(stmt)


def upsert_candidate(
    conn,
    lid_a: int,
    lid_b: int,
    result: dict[str, Any],
    *,
    run_ts: str,
) -> None:
    """
    Insert or update a candidate row.  Existing operator status is preserved
    on update.  Stable ordering: lid_a < lid_b always.

    run_ts is the ISO timestamp of the current detection run, stored in
    last_evaluated_at so stale detection can identify rows not seen in
    a subsequent run.
    """
    a, b = min(lid_a, lid_b), max(lid_a, lid_b)
    now = datetime.now().isoformat()
    evidence = json.dumps(result["reasons"])
    differences = json.dumps(result["differences"])
    score = result["score"]
    classification = result["classification"]

    existing = conn.execute(
        "SELECT id, status FROM listing_duplicate_candidates WHERE listing_id_a=? AND listing_id_b=?",
        (a, b),
    ).fetchone()

    if existing:
        # Preserve operator status; update scoring and mark as evaluated
        conn.execute(
            """
            UPDATE listing_duplicate_candidates
            SET score=?, classification=?, evidence=?, differences=?,
                last_evaluated_at=?, updated_at=?,
                status = CASE
                    WHEN status = 'STALE' THEN 'OPEN'
                    ELSE status
                END
            WHERE listing_id_a=? AND listing_id_b=?
            """,
            (score, classification, evidence, differences, run_ts, now, a, b),
        )
    else:
        conn.execute(
            """
            INSERT INTO listing_duplicate_candidates
            (listing_id_a, listing_id_b, score, classification, evidence, differences,
             status, last_evaluated_at, created_at, updated_at)
            VALUES (?,?,?,?,?,?,'OPEN',?,?,?)
            """,
            (a, b, score, classification, evidence, differences, run_ts, now, now),
        )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run_detection(*, dry_run: bool = False, conn=None) -> dict[str, Any]:
    """
    Run the full detection pipeline.

    dry_run=True: score candidates but do not write to the database.

    Returns summary counts by classification and a list of top candidates.
    """
    should_close = conn is None
    conn = conn or database.get_connection()

    try:
        ensure_schema(conn)
        pairs = generate_candidates(conn)
        run_ts = datetime.now().isoformat()
        evaluated_pairs: set[tuple[int, int]] = set()

        results: list[dict] = []
        for a_data, b_data in pairs:
            result = score_pair(a_data, b_data)
            result["listing_id_a"] = a_data["id"]
            result["listing_id_b"] = b_data["id"]
            result["source_listing_id_a"] = a_data["source_listing_id"]
            result["source_listing_id_b"] = b_data["source_listing_id"]
            results.append(result)

            if not dry_run:
                upsert_candidate(conn, a_data["id"], b_data["id"], result, run_ts=run_ts)
                pair_key = (min(a_data["id"], b_data["id"]), max(a_data["id"], b_data["id"]))
                evaluated_pairs.add(pair_key)

        if not dry_run:
            # Mark OPEN pairs not seen in this run as STALE.
            # Preserves CONFIRMED_SAME / CONFIRMED_DIFFERENT / DISMISSED.
            if evaluated_pairs:
                placeholders = ",".join("(?,?)" for _ in evaluated_pairs)
                params: list = []
                for pa, pb in evaluated_pairs:
                    params.extend([pa, pb])
                conn.execute(
                    f"""
                    UPDATE listing_duplicate_candidates
                    SET status = 'STALE', updated_at = ?
                    WHERE status = 'OPEN'
                      AND (listing_id_a, listing_id_b) NOT IN ({placeholders})
                    """,
                    [run_ts] + params,
                )
            else:
                # No candidates at all — mark every OPEN row stale
                conn.execute(
                    "UPDATE listing_duplicate_candidates SET status='STALE', updated_at=? WHERE status='OPEN'",
                    (run_ts,),
                )
            conn.commit()

        by_class: dict[str, int] = {}
        for r in results:
            by_class[r["classification"]] = by_class.get(r["classification"], 0) + 1

        top_10 = sorted(results, key=lambda x: x["score"], reverse=True)[:10]

        return {
            "total_candidates": len(results),
            "by_classification": by_class,
            "top_candidates": top_10,
        }

    finally:
        if should_close:
            conn.close()


def score_listing_pair(listing_id_a: int, listing_id_b: int, *, conn=None) -> dict[str, Any]:
    """Score a single explicit listing pair and return the result dict."""
    should_close = conn is None
    conn = conn or database.get_connection()
    try:
        def _fetch(lid):
            row = conn.execute(
                "SELECT id, source_id, source_listing_id, current_price, current_mileage, "
                "current_seller, current_description, current_options FROM listings WHERE id=?",
                (lid,),
            ).fetchone()
            if row is None:
                raise ValueError(f"listing {lid} not found")
            snap = _get_snapshot_fields(lid, conn)
            return _listing_data(row, snap)

        a_data = _fetch(listing_id_a)
        b_data = _fetch(listing_id_b)
        return score_pair(a_data, b_data)
    finally:
        if should_close:
            conn.close()
