"""
CarHunter v3.0 — Cross-Source Duplicate Detection
==================================================
Detects likely duplicate vehicle listings that appear on more than one
source (e.g. AutoScout24 and PKW.de) without performing any automatic
vehicle merge.

SAFETY CONTRACT
---------------
* Detection is read-only with respect to listings, vehicles,
  source_listings, source_snapshots, and the cars compatibility table.
* The only writes are to listing_duplicate_candidates.
* No Vehicle.vehicle_id is ever modified.
* No Listing is ever deleted or merged.
* VIN-based automatic resolution remains the sole auto-merge path
  (implemented separately in database.resolve_canonical_vehicle_links).

DESIGN
------
1. Blocking
   Candidate pairs are generated by matching on tight price + mileage
   bands (≤3 % price difference, ≤5 % + 1 000 km mileage difference)
   across listings from DIFFERENT sources.  Only ACTIVE listings are
   considered.

2. Scoring
   Each candidate pair is scored using explicit deterministic signals:

   VERY_STRONG  (≥85): only reachable with multiple strong signals
   STRONG       (≥60): consistent key fields
   POSSIBLE     (≥35): some overlapping fields
   LOW          (<35):  weak coincidence

3. Persistence
   Results are stored in listing_duplicate_candidates with stable
   pair ordering (min_id, max_id) to guarantee idempotency.
   Operator decisions (CONFIRMED_SAME / CONFIRMED_DIFFERENT / DISMISSED)
   are preserved on rescore.
"""

from __future__ import annotations

import ast
import json
import re
import unicodedata
from datetime import datetime
from typing import Any

import database


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------

_DDL = """
CREATE TABLE IF NOT EXISTS listing_duplicate_candidates (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    listing_id_a      INTEGER NOT NULL,
    listing_id_b      INTEGER NOT NULL,
    score             INTEGER NOT NULL,
    classification    TEXT NOT NULL,
    evidence          TEXT NOT NULL DEFAULT '[]',
    differences       TEXT NOT NULL DEFAULT '[]',
    status            TEXT NOT NULL DEFAULT 'OPEN',
    last_evaluated_at TEXT,
    operator_comment  TEXT,
    reviewed_at       TEXT,
    created_at        TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(listing_id_a, listing_id_b),
    FOREIGN KEY (listing_id_a) REFERENCES listings(id),
    FOREIGN KEY (listing_id_b) REFERENCES listings(id),
    CHECK (listing_id_a < listing_id_b),
    CHECK (status IN ('OPEN','CONFIRMED_SAME','CONFIRMED_DIFFERENT','UNSURE','DISMISSED','STALE'))
);
CREATE INDEX IF NOT EXISTS idx_ldc_status
    ON listing_duplicate_candidates(status);
CREATE INDEX IF NOT EXISTS idx_ldc_classification
    ON listing_duplicate_candidates(classification, score DESC);
"""

# Columns added after initial schema deployment — applied by ensure_schema().
# These handle the case where a database was initially created with _DDL but
# before these columns existed.  The CHECK constraint update is handled by
# _migrate_check_constraint() below.
_MIGRATIONS = [
    "ALTER TABLE listing_duplicate_candidates ADD COLUMN last_evaluated_at TEXT",
    "ALTER TABLE listing_duplicate_candidates ADD COLUMN operator_comment TEXT",
    "ALTER TABLE listing_duplicate_candidates ADD COLUMN reviewed_at TEXT",
]

# The new CHECK constraint that must be present for STALE and UNSURE to work.
_REQUIRED_CHECK = "('OPEN','CONFIRMED_SAME','CONFIRMED_DIFFERENT','UNSURE','DISMISSED','STALE')"

# ---------------------------------------------------------------------------
# Scoring weights
# ---------------------------------------------------------------------------

_W_PRICE_EXACT    = 20   # equal price
_W_PRICE_CLOSE    = 20   # price within 1%
_W_MILEAGE_EXACT  = 20   # equal mileage
_W_MILEAGE_CLOSE  = 15   # mileage within 2% or 500 km
_W_SELLER_MATCH   = 20   # normalised dealer name match
_W_SELLER_CONTACT = 15   # normalised seller contact match
_W_SELLER_RELATED = 10   # conservative shared company identity
_W_MAKE_MODEL     =  8   # same source-neutral make/model
_W_ENGINE_FAMILY  =  8   # same explicit engine family (TDI/TFSI)
_W_MODEL_VARIANT  =  6   # same explicit designation (35/40/45)
_W_REG_YEAR       = 10   # same registration year
_W_TITLE_HIGH     = 10   # normalised title similarity ≥ 0.85
_W_TITLE_MOD      =  5   # normalised title similarity ≥ 0.60
_W_DESC_HIGH      =  8   # long shared description tokens ≥ 0.70
_W_POWER_MATCH    =  5   # same power (hp) within 5%
_W_TRANSMISSION   =  3   # same gearbox family
_W_DRIVETRAIN     =  3   # same drive type
_W_COLOUR_MATCH   =  2   # same colour family

_PENALTY_VIN_CONFLICT   = -80   # conflicting VINs → never strong
_PENALTY_REG_MISMATCH   = -15   # different reg year
_PENALTY_POWER_CONFLICT = -10   # clearly different engine (>15% difference)
_PENALTY_SELLER_NEG     = -12   # explicitly different seller (when both known)
_PENALTY_TRANSMISSION   = -23   # manual vs automatic
_PENALTY_DRIVETRAIN     =  -8   # incompatible known drive types
_PENALTY_COLOUR         = -10   # confidently different known colours
_PENALTY_IDENTITY       = -60   # reliable engine/designation contradiction

_CONTRADICTION_SCORE_CAP = 34

_CLASSIFICATION_VERY_STRONG = "VERY_STRONG"
_CLASSIFICATION_STRONG      = "STRONG"
_CLASSIFICATION_POSSIBLE    = "POSSIBLE"
_CLASSIFICATION_LOW         = "LOW"


# ---------------------------------------------------------------------------
# Normalisation helpers
# ---------------------------------------------------------------------------

def _norm_text(s: str | None) -> str:
    if not s:
        return ""
    s = unicodedata.normalize("NFC", str(s))
    s = s.upper()
    s = re.sub(r"[^\w\s]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


_LEGAL_SUFFIXES = re.compile(
    r"\b(GMBH|CO|KG|AG|GBMR|MBHG|UND|&|E\.K\.|EK|SARL|SAS|SRL|BV)\b",
    re.IGNORECASE,
)

# Common generic dealership prefixes that appear on one side but not the other.
# Stripping these before token comparison avoids false "different seller" verdicts
# when e.g. PKW.de stores "Autohaus Schmidt" vs AS24 "Schmidt GmbH".
_DEALER_PREFIXES = re.compile(
    r"\b(AUTOHAUS|AUTOCENTER|AUTOGALERIE|AUTOZENTRUM|AUTOPARK|AUTOLAND|AUTOMOBILE|"
    r"AUTO|FAHRZEUGHAUS|FAHRZEUGCENTER|FAHRZEUGTECHNIK|"
    r"GARAGE|KFZHANDEL|KFZ|MOTOREN|GRUPPE)\b",
    re.IGNORECASE,
)


def _seller_mapping(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        return value
    if not isinstance(value, str) or not value.lstrip().startswith("{"):
        return {}
    for parser in (json.loads, ast.literal_eval):
        try:
            parsed = parser(value)
        except (ValueError, SyntaxError, TypeError, json.JSONDecodeError):
            continue
        if isinstance(parsed, dict):
            dealer = parsed.get("dealer")
            return {**dealer, **parsed} if isinstance(dealer, dict) else parsed
    return {}


def _extract_seller_field(s: Any, field: str) -> str:
    if not s:
        return ""
    mapping = _seller_mapping(s)
    aliases = {
        "companyName": ("companyName", "company_name", "seller_name", "name"),
        "contactName": ("contactName", "contact_name"),
    }
    for alias in aliases.get(field, (field,)):
        if mapping.get(alias):
            return str(mapping[alias]).strip()
    match = re.search(
        rf"['\"]?{re.escape(field)}['\"]?\s*[:=]\s*['\"]([^'\"]+)['\"]",
        str(s),
        re.IGNORECASE,
    )
    return match.group(1).strip() if match else ""


def _extract_company_name(s: Any) -> str:
    """Extract the bare company name from raw seller strings.

    Handles:
    - Python dict repr: "{'companyName': 'Foo GmbH', ...}"
    - JSON string:      '{"companyName": "Foo GmbH"}'
    - Plain string:     "Foo GmbH"
    """
    if not s:
        return ""
    company = _extract_seller_field(s, "companyName")
    if company:
        return company
    if str(s).lstrip().startswith(("{", "[")):
        return ""
    return str(s)


def _extract_contact_name(s: Any) -> str:
    return _extract_seller_field(s, "contactName")


def _norm_seller(s: str | None) -> str:
    """Normalise a seller/dealer string for token-similarity comparison.

    Steps:
    1. Extract companyName from dict/JSON repr when present.
    2. Upper-case and strip punctuation via _norm_text.
    3. Remove legal entity suffixes (GmbH, KG, …).
    4. Remove common generic dealership prefixes (Autohaus, Auto, …).
    5. Collapse whitespace.

    The result is suitable for token similarity — stripping both legal
    suffixes and generic prefixes means "Autohaus Schmidt GmbH" and
    "Schmidt" resolve to the same core token "SCHMIDT".
    """
    if not s:
        return ""
    s = _extract_company_name(s)
    s = _norm_text(s)
    s = _LEGAL_SUFFIXES.sub(" ", s)
    s = _DEALER_PREFIXES.sub(" ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def _seller_identity(s: Any) -> dict[str, str]:
    raw = str(s or "")
    company = _extract_company_name(raw)
    contact = _extract_contact_name(raw)
    return {
        "seller_company": company,
        "seller_contact": contact,
        "seller_company_norm": _norm_seller(company),
        "seller_contact_norm": _norm_text(contact),
    }


def _company_similarity(a: str, b: str) -> tuple[str, float]:
    """Return exact, related, or different for two normalized companies."""
    if not a or not b:
        return "unknown", 0.0
    similarity = _token_similarity(a, b)
    if a == b or similarity >= 0.70:
        return "exact", similarity

    tokens_a = {
        token for token in a.split()
        if len(token) >= 3 and token not in _GENERIC_COMPANY_TOKENS
    }
    tokens_b = {
        token for token in b.split()
        if len(token) >= 3 and token not in _GENERIC_COMPANY_TOKENS
    }
    shared = tokens_a & tokens_b
    if shared:
        containment = len(shared) / min(len(tokens_a), len(tokens_b))
        if containment >= 0.50:
            return "related", containment
    return "different", similarity


_GENERIC_CONTACT_TOKENS = {
    "TEAM", "VERKAUF", "VERKAUFSTEAM", "IHRE", "IHR", "SALES",
}
_GENERIC_COMPANY_TOKENS = {"DAS", "DER", "DIE", "THE", "UND"}


def _contact_matches_seller(contact: str, seller_company: str) -> bool:
    contact_tokens = {
        token for token in _norm_text(contact).split()
        if len(token) >= 3 and token not in _GENERIC_CONTACT_TOKENS
    }
    seller_tokens = set(_norm_text(seller_company).split())
    return len(contact_tokens) >= 2 and contact_tokens <= seller_tokens


def _seller_contact_match(a: dict[str, str], b: dict[str, str]) -> str:
    if (
        a["seller_contact_norm"]
        and a["seller_contact_norm"] == b["seller_contact_norm"]
    ):
        return a["seller_contact"]
    if (
        a["seller_contact"]
        and _contact_matches_seller(a["seller_contact"], b["seller_company"])
    ):
        return a["seller_contact"]
    if (
        b["seller_contact"]
        and _contact_matches_seller(b["seller_contact"], a["seller_company"])
    ):
        return b["seller_contact"]
    return ""


_COLOUR_MAP = {
    "grau": "grey", "gray": "grey", "grey": "grey", "grijs": "grey",
    "silbergrau": "grey",
    "weiss": "white", "white": "white", "weiß": "white", "wit": "white",
    "schwarz": "black", "black": "black", "zwart": "black",
    "silber": "silver", "silver": "silver", "zilver": "silver",
    "blau": "blue", "blue": "blue", "blauw": "blue",
    "rot": "red", "red": "red", "rood": "red",
    "grün": "green", "green": "green", "groen": "green",
    "braun": "brown", "brown": "brown", "bruin": "brown",
    "beige": "beige",
    "orange": "orange", "oranje": "orange",
    "gelb": "yellow", "yellow": "yellow", "geel": "yellow",
    "violett": "purple", "purple": "purple", "paars": "purple",
}

def _norm_colour(s: str | None) -> str:
    if not s:
        return ""
    key = s.lower().strip()
    if key in _COLOUR_MAP:
        return _COLOUR_MAP[key]
    tokens = re.findall(r"[\wäöüß]+", key)
    mapped = {_COLOUR_MAP[token] for token in tokens if token in _COLOUR_MAP}
    return mapped.pop() if len(mapped) == 1 else key


_DRIVE_MAP = {
    "allrad": "awd", "4wd": "awd", "awd": "awd", "quattro": "awd",
    "4x4": "awd", "4motion": "awd",
    "front": "fwd", "fwd": "fwd", "frontantrieb": "fwd",
    "rear": "rwd", "rwd": "rwd", "hinterrad": "rwd",
}

def _norm_drive(s: str | None) -> str:
    if not s:
        return ""
    return _DRIVE_MAP.get(s.lower().strip(), s.lower().strip())


_GEARBOX_MAP = {
    "automatik": "auto", "automatic": "auto", "auto": "auto",
    "dsg": "auto", "s tronic": "auto", "s-tronic": "auto",
    "tiptronic": "auto", "pdk": "auto", "cvt": "auto",
    "schaltgetriebe": "manual", "manual": "manual", "manuell": "manual",
}

def _norm_gearbox(s: str | None) -> str:
    if not s:
        return ""
    return _GEARBOX_MAP.get(s.lower().strip(), s.lower().strip())


_ENGINE_FAMILY_PATTERN = re.compile(
    r"(?<![A-Z])(TDI|TFSI|FSI|TSI)(?![A-Z])",
    re.IGNORECASE,
)
_MODEL_DESIGNATION_PATTERN = re.compile(
    r"(?<!\d)(25|30|35|40|45|50|55|60)\s*(TDI|TFSI|FSI|TSI)(?![A-Z])",
    re.IGNORECASE,
)


def _norm_fuel_family(value: str | None) -> str:
    normalized = _norm_text(value)
    if any(token in normalized for token in ("DIESEL", "TDI")):
        return "diesel"
    if any(
        token in normalized
        for token in ("BENZIN", "PETROL", "GASOLINE", "TFSI", "FSI", "TSI")
    ):
        return "petrol"
    if any(token in normalized for token in ("ELEKTRO", "ELECTRIC")):
        return "electric"
    return ""


def _vehicle_signature(data: dict[str, Any]) -> dict[str, str]:
    """Extract only high-confidence identity tokens from structured data/title."""
    title = str(data.get("title") or "")
    structured_variant = str(data.get("model_designation") or "")
    structured_designation = (
        re.fullmatch(
            r"(25|30|35|40|45|50|55|60)",
            structured_variant.strip(),
        )
        or _MODEL_DESIGNATION_PATTERN.search(structured_variant)
    )
    designation_match = _MODEL_DESIGNATION_PATTERN.search(title)
    structured_engine = _ENGINE_FAMILY_PATTERN.search(
        f"{data.get('engine_family') or ''} {structured_variant}"
    )
    engine_match = structured_engine or _ENGINE_FAMILY_PATTERN.search(title)
    engine_family = engine_match.group(1).upper() if engine_match else ""
    fuel_family = _norm_fuel_family(data.get("fuel"))
    if engine_family == "TDI":
        fuel_family = "diesel"
    elif engine_family in {"TFSI", "FSI", "TSI"}:
        fuel_family = "petrol"

    make = _norm_text(data.get("make"))
    model = _norm_text(data.get("model"))
    if not make or not model:
        title_tokens = _norm_text(title).split()
        if len(title_tokens) >= 2:
            make = make or title_tokens[0]
            model = model or title_tokens[1]

    return {
        "make": make,
        "model": model,
        "engine_family": engine_family,
        "fuel_family": fuel_family,
        "model_designation": (
            structured_designation.group(1)
            if structured_designation
            else designation_match.group(1) if designation_match else ""
        ),
    }


def _token_similarity(a: str, b: str) -> float:
    """Jaccard similarity on word tokens."""
    if not a or not b:
        return 0.0
    ta = set(_norm_text(a).split())
    tb = set(_norm_text(b).split())
    if not ta or not tb:
        return 0.0
    intersection = ta & tb
    union = ta | tb
    return len(intersection) / len(union)


def _long_common_tokens(a: str, b: str) -> float:
    """Token overlap on words ≥5 chars — filters out common stop words."""
    if not a or not b:
        return 0.0
    ta = {w for w in _norm_text(a).split() if len(w) >= 5}
    tb = {w for w in _norm_text(b).split() if len(w) >= 5}
    if not ta or not tb:
        return 0.0
    return len(ta & tb) / max(len(ta), len(tb))


# ---------------------------------------------------------------------------
# Snapshot field extractor
# ---------------------------------------------------------------------------

def _get_snapshot_fields(listing_id: int, conn) -> dict[str, Any]:
    """
    Return merged extracted_fields for a listing, combining all snapshots
    so that detail fields present in an older snapshot are not lost if the
    latest snapshot is a summary-only re-scrape.
    Earlier snapshots are applied first (lowest precedence); later snapshots
    override, but only for non-empty values.
    """
    rows = conn.execute(
        """
        SELECT ss.extracted_fields
        FROM source_snapshots ss
        JOIN source_listings sl
          ON sl.source_id = ss.source_id
         AND sl.source_listing_id = ss.source_listing_id
        JOIN listings l ON l.source_listing_row_id = sl.id
        WHERE l.id = ?
        ORDER BY ss.id ASC
        """,
        (listing_id,),
    ).fetchall()
    merged: dict[str, Any] = {}
    for row in rows:
        if row and row[0]:
            try:
                fields = json.loads(row[0])
                for k, v in fields.items():
                    if v is not None and v != "" and v != [] and v != {}:
                        merged[k] = v
            except (ValueError, TypeError):
                pass
    return merged


def _listing_data(listing_row, snap: dict[str, Any]) -> dict[str, Any]:
    """
    Build the data dict used for scoring.

    TEMPORAL SAFETY RULE:
    Mutable fields that reflect current market state — price, mileage,
    seller — are taken EXCLUSIVELY from the listings table columns
    (current_price, current_mileage, current_seller).  Snapshot fields
    are never allowed to override these even if the snapshot is richer,
    because an older snapshot may reflect a different price/mileage/owner.

    Stable descriptive fields — title, year, colour, power, drivetrain,
    transmission, VIN, make, model, first_registration — may be enriched
    from historical snapshots because they do not change meaningfully
    across a vehicle's listing lifetime.
    """
    lid, source_id, source_listing_id, price, mileage, seller, description, options = listing_row

    # Prefer description; fall back to options JSON as comparable text
    desc_text = description or snap.get("description")
    if not desc_text and options:
        try:
            opts = json.loads(options) if isinstance(options, str) else options
            if isinstance(opts, list):
                desc_text = " ".join(str(o) for o in opts)
        except (ValueError, TypeError):
            desc_text = str(options)

    return {
        "id": lid,
        "source_id": source_id,
        "source_listing_id": source_listing_id,
        # ── MUTABLE (current state from listings table only) ───────────────
        "price": price,          # current_price — never from snapshot
        "mileage": mileage,      # current_mileage — never from snapshot
        "seller": seller,        # current_seller — never from snapshot
        # ── STABLE DESCRIPTIVE (snapshot enrichment allowed) ──────────────
        "description": desc_text,
        "options": options,
        "title": snap.get("title"),
        "year": snap.get("year"),
        "first_registration": snap.get("first_registration"),
        "colour": snap.get("colour") or snap.get("color"),
        "power_hp": snap.get("power_hp") or snap.get("hp"),
        "drivetrain": snap.get("drivetrain") or snap.get("drive"),
        "transmission": snap.get("transmission") or snap.get("gearbox"),
        "vin": snap.get("vin"),
        "make": snap.get("make"),
        "model": snap.get("model"),
        "fuel": snap.get("fuel") or snap.get("fuel_type"),
        "engine_family": snap.get("engine_family"),
        "model_designation": (
            snap.get("model_designation")
            or snap.get("model_variant")
            or snap.get("variant")
        ),
    }


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------

def score_pair(a: dict[str, Any], b: dict[str, Any]) -> dict[str, Any]:
    """
    Score a candidate pair and return a result dict with:
      score, classification, reasons (evidence), differences

    VIN VETO: conflicting VINs are an absolute veto for STRONG/VERY_STRONG
    regardless of all other signals.  The classification is capped at POSSIBLE
    and the score is zeroed when VINs conflict.
    """
    score = 0
    reasons: list[str] = []
    differences: list[str] = []
    hard_contradiction = False

    # ── VIN check ──────────────────────────────────────────────────────────
    vin_a = (a.get("vin") or "").strip().upper()
    vin_b = (b.get("vin") or "").strip().upper()
    if vin_a and vin_b:
        if vin_a == vin_b:
            # VIN match is handled by ARCH-007 auto-merge; record as evidence.
            reasons.append("exact VIN match")
            score += 40
        else:
            hard_contradiction = True
            differences.append(f"conflicting VIN: {vin_a} vs {vin_b}")

    # ── Price ───────────────────────────────────────────────────────────────
    pa, pb = _to_int(a.get("price")), _to_int(b.get("price"))
    if pa is not None and pb is not None:
        diff_pct = abs(pa - pb) / max(pa, pb)
        if pa == pb:
            score += _W_PRICE_EXACT
            reasons.append(f"exact price: €{pa:,}".replace(",", "."))
        elif diff_pct <= 0.01:
            score += _W_PRICE_CLOSE
            reasons.append(f"close price: €{pa:,} vs €{pb:,}".replace(",", "."))
        elif diff_pct <= 0.05:
            score += _W_PRICE_EXACT // 2
            reasons.append(f"close price: €{pa:,} vs €{pb:,}".replace(",", "."))
        else:
            differences.append(f"different price: €{pa:,} vs €{pb:,} ({diff_pct:.0%})".replace(",", "."))

    # ── Mileage ─────────────────────────────────────────────────────────────
    ma = _to_int(a.get("mileage"))
    mb = _to_int(b.get("mileage"))
    if ma is not None and mb is not None:
        diff_km = abs(ma - mb)
        diff_pct = diff_km / max(ma, mb)
        if ma == mb:
            score += _W_MILEAGE_EXACT
            reasons.append(f"exact mileage: {ma:,} km".replace(",", "."))
        elif diff_km <= 500 or diff_pct <= 0.02:
            score += _W_MILEAGE_CLOSE
            reasons.append(f"close mileage: {ma:,} vs {mb:,} km".replace(",", "."))
        elif diff_pct <= 0.05:
            score += _W_MILEAGE_EXACT // 4
            reasons.append(f"close mileage: {ma:,} vs {mb:,} km".replace(",", "."))
        else:
            differences.append(f"different mileage: {ma:,} vs {mb:,} km ({diff_pct:.0%})".replace(",", "."))

    # ── Seller ──────────────────────────────────────────────────────────────
    seller_a = _seller_identity(a.get("seller"))
    seller_b = _seller_identity(b.get("seller"))
    contact_match = _seller_contact_match(seller_a, seller_b)
    if contact_match:
        score += _W_SELLER_CONTACT
        reasons.append(f"same seller contact: {contact_match}")

    if seller_a["seller_company_norm"] and seller_b["seller_company_norm"]:
        relationship, _ = _company_similarity(
            seller_a["seller_company_norm"], seller_b["seller_company_norm"]
        )
        if relationship == "exact":
            score += _W_SELLER_MATCH
            reasons.append(f"same seller company: {seller_a['seller_company']}")
        elif relationship == "related":
            score += _W_SELLER_RELATED
            reasons.append(
                "related seller companies: "
                f"{seller_a['seller_company']} / {seller_b['seller_company']}"
            )
        else:
            score += _PENALTY_SELLER_NEG
            differences.append(
                f"seller conflict: {seller_a['seller_company']} vs "
                f"{seller_b['seller_company']}"
            )

    # ── Vehicle signature ───────────────────────────────────────────────────
    signature_a = _vehicle_signature(a)
    signature_b = _vehicle_signature(b)
    if (
        signature_a["make"] and signature_b["make"]
        and signature_a["model"] and signature_b["model"]
        and signature_a["make"] == signature_b["make"]
        and signature_a["model"] == signature_b["model"]
    ):
        score += _W_MAKE_MODEL
        reasons.append(
            f"same make/model: {signature_a['make'].title()} {signature_a['model']}"
        )

    engine_a = signature_a["engine_family"]
    engine_b = signature_b["engine_family"]
    if engine_a and engine_b:
        if engine_a == engine_b:
            score += _W_ENGINE_FAMILY
            reasons.append(f"same engine family: {engine_a}")
        else:
            score += _PENALTY_IDENTITY
            hard_contradiction = True
            differences.append(f"engine conflict: {engine_a} vs {engine_b}")
    elif signature_a["fuel_family"] and signature_b["fuel_family"]:
        if signature_a["fuel_family"] == signature_b["fuel_family"]:
            score += _W_ENGINE_FAMILY // 2
            reasons.append(
                f"compatible fuel family: {signature_a['fuel_family']}"
            )
        else:
            score += _PENALTY_IDENTITY
            hard_contradiction = True
            differences.append(
                f"fuel family conflict: {signature_a['fuel_family']} vs "
                f"{signature_b['fuel_family']}"
            )

    designation_a = signature_a["model_designation"]
    designation_b = signature_b["model_designation"]
    if designation_a and designation_b:
        if designation_a == designation_b:
            score += _W_MODEL_VARIANT
            reasons.append(f"same model designation: {designation_a}")
        else:
            score += _PENALTY_IDENTITY
            hard_contradiction = True
            differences.append(
                f"model designation conflict: {designation_a} vs {designation_b}"
            )

    # ── Registration year ───────────────────────────────────────────────────
    ya = _reg_year(a)
    yb = _reg_year(b)
    if ya and yb:
        if ya == yb:
            score += _W_REG_YEAR
            reasons.append(f"same registration year: {ya}")
        else:
            score += _PENALTY_REG_MISMATCH
            differences.append(f"different year: {ya} vs {yb}")

    # ── Title similarity ────────────────────────────────────────────────────
    ta, tb = a.get("title"), b.get("title")
    if ta and tb:
        # Use token-overlap but also reward when the shorter title's tokens
        # are a subset of the longer title (abbreviated form).
        ta_norm = set(_norm_text(ta).split())
        tb_norm = set(_norm_text(tb).split())
        shorter, longer = (ta_norm, tb_norm) if len(ta_norm) <= len(tb_norm) else (tb_norm, ta_norm)
        containment = len(shorter & longer) / len(shorter) if shorter else 0.0
        jaccard = len(ta_norm & tb_norm) / len(ta_norm | tb_norm) if (ta_norm | tb_norm) else 0.0
        sim = max(containment, jaccard)
        if sim >= 0.85:
            score += _W_TITLE_HIGH
            reasons.append(f"high title similarity ({sim:.0%}): {ta!r}")
        elif sim >= 0.60:
            score += _W_TITLE_MOD
            reasons.append(f"moderate title similarity ({sim:.0%})")
        else:
            differences.append(f"low title similarity ({sim:.0%}): {ta!r} vs {tb!r}")

    # ── Description overlap ─────────────────────────────────────────────────
    da, db = a.get("description"), b.get("description")
    if da and db and len(da) > 100 and len(db) > 100:
        sim = _long_common_tokens(da, db)
        if sim >= 0.70:
            score += _W_DESC_HIGH
            reasons.append(f"high description/equipment overlap ({sim:.0%})")
        elif sim >= 0.40:
            score += _W_DESC_HIGH // 2
            reasons.append(f"moderate description overlap ({sim:.0%})")

    # ── Power ───────────────────────────────────────────────────────────────
    hpa = _to_int(a.get("power_hp"))
    hpb = _to_int(b.get("power_hp"))
    if hpa and hpb:
        diff_pct = abs(hpa - hpb) / max(hpa, hpb)
        if diff_pct <= 0.05:
            score += _W_POWER_MATCH
            if hpa == hpb:
                reasons.append(f"same power: {hpa} hp")
            else:
                reasons.append(f"compatible power: {hpa} vs {hpb} hp")
        elif diff_pct > 0.15:
            score += _PENALTY_POWER_CONFLICT
            differences.append(f"power conflict: {hpa} hp vs {hpb} hp")

    # ── Transmission ────────────────────────────────────────────────────────
    ga = _norm_gearbox(a.get("transmission"))
    gb = _norm_gearbox(b.get("transmission"))
    if ga and gb:
        if ga == gb:
            score += _W_TRANSMISSION
            reasons.append(f"same transmission: {ga}")
        else:
            score += _PENALTY_TRANSMISSION
            differences.append(f"transmission conflict: {ga} vs {gb}")

    # ── Drivetrain ──────────────────────────────────────────────────────────
    dra = _norm_drive(a.get("drivetrain"))
    drb = _norm_drive(b.get("drivetrain"))
    if dra and drb:
        if dra == drb:
            score += _W_DRIVETRAIN
            reasons.append(f"same drivetrain: {dra}")
        else:
            score += _PENALTY_DRIVETRAIN
            differences.append(f"drivetrain conflict: {dra} vs {drb}")

    # ── Colour ──────────────────────────────────────────────────────────────
    ca = _norm_colour(a.get("colour"))
    cb = _norm_colour(b.get("colour"))
    if ca and cb:
        if ca == cb:
            score += _W_COLOUR_MATCH
            reasons.append(f"same colour: {ca}")
        else:
            score += _PENALTY_COLOUR
            differences.append(f"colour conflict: {ca} vs {cb}")

    score = max(0, min(100, score))

    # VIN, engine-family, fuel-family, and reliable designation conflicts
    # override coincidental price/mileage/year similarity.
    if hard_contradiction:
        score = min(score, _CONTRADICTION_SCORE_CAP)
        classification = _classify(score)
    else:
        classification = _classify(score)

    return {
        "score": score,
        "classification": classification,
        "reasons": reasons,
        "differences": differences,
    }


def _reg_year(d: dict) -> int | None:
    for value in (d.get("year"), d.get("first_registration")):
        match = re.search(r"\b((?:19|20)\d{2})\b", str(value or ""))
        if match:
            return int(match.group(1))
    return None


def _to_int(v) -> int | None:
    try:
        return int(v) if v is not None else None
    except (ValueError, TypeError):
        return None


def _classify(score: int) -> str:
    if score >= 85:
        return _CLASSIFICATION_VERY_STRONG
    if score >= 60:
        return _CLASSIFICATION_STRONG
    if score >= 35:
        return _CLASSIFICATION_POSSIBLE
    return _CLASSIFICATION_LOW


# ---------------------------------------------------------------------------
# Candidate generation
# ---------------------------------------------------------------------------

_CANDIDATE_QUERY = """
SELECT
    a.id, a.source_id, a.source_listing_id, a.current_price, a.current_mileage,
    a.current_seller, a.current_description, a.current_options,
    b.id, b.source_id, b.source_listing_id, b.current_price, b.current_mileage,
    b.current_seller, b.current_description, b.current_options
FROM listings a
JOIN listings b ON b.id > a.id
WHERE a.source_id != b.source_id
  AND a.availability = 'ACTIVE'
  AND b.availability = 'ACTIVE'
  AND a.current_price IS NOT NULL
  AND b.current_price IS NOT NULL
  AND ABS(CAST(a.current_price AS REAL) - CAST(b.current_price AS REAL))
      <= (a.current_price * 0.03 + 200)
  AND (
    a.current_mileage IS NULL
    OR b.current_mileage IS NULL
    OR ABS(CAST(a.current_mileage AS REAL) - CAST(b.current_mileage AS REAL))
       <= (a.current_mileage * 0.05 + 1000)
  )
"""


def generate_candidates(conn) -> list[tuple[dict, dict]]:
    """
    Return (listing_a_data, listing_b_data) pairs from different sources
    that pass the price + mileage blocking filter.
    """
    rows = conn.execute(_CANDIDATE_QUERY).fetchall()
    pairs = []
    for row in rows:
        a_row = row[:8]
        b_row = row[8:]
        snap_a = _get_snapshot_fields(a_row[0], conn)
        snap_b = _get_snapshot_fields(b_row[0], conn)
        pairs.append((_listing_data(a_row, snap_a), _listing_data(b_row, snap_b)))
    return pairs


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------

def ensure_schema(conn) -> None:
    """Create detection tables and indexes if they do not exist, then apply
    any pending schema migrations.

    Does NOT commit; the caller controls the transaction.

    Migration strategy
    ------------------
    SQLite does not support ALTER TABLE … MODIFY CONSTRAINT, so updating a
    CHECK constraint requires the standard rename-create-copy-drop approach.
    We detect the old constraint by inspecting sqlite_master and, if found,
    perform a transaction-safe table reconstruction that preserves every
    existing row, operator decision, and timestamp.

    After reconstruction, additive column migrations (ALTER TABLE ADD COLUMN)
    are applied idempotently for the remaining new columns.

    All operations are idempotent: calling ensure_schema() twice in a row is
    safe and produces no side effects.
    """
    # ── 1. Create table if it does not exist yet ────────────────────────────
    for stmt in _DDL.strip().split(";"):
        stmt = stmt.strip()
        if stmt:
            conn.execute(stmt)

    # ── 2. Migrate CHECK constraint if the old (incomplete) one is present ──
    _migrate_check_constraint(conn)

    # ── 3. Additive column migrations (idempotent) ──────────────────────────
    for migration in _MIGRATIONS:
        try:
            conn.execute(migration)
        except Exception:
            pass  # column already exists


def _migrate_check_constraint(conn) -> None:
    """
    If listing_duplicate_candidates has the old CHECK constraint that lacks
    STALE and UNSURE, reconstruct the table in-place preserving all data.

    The reconstruction uses SQLite's recommended rename-copy-drop pattern:
      1. Rename old table to _ldc_old
      2. Create new table with correct schema
      3. Copy all columns common to both schemas
      4. Drop old table
      5. Recreate indexes (CREATE INDEX IF NOT EXISTS is a no-op if present)

    The entire operation is run within the caller's transaction so a failure
    leaves the database unchanged.
    """
    row = conn.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name='listing_duplicate_candidates'"
    ).fetchone()
    if row is None:
        return  # table does not exist yet — DDL above will create it fresh
    existing_sql = row[0] or ""
    if _REQUIRED_CHECK in existing_sql:
        return  # already up to date

    # Old table exists with insufficient CHECK — reconstruct it.
    # Determine which columns currently exist so we copy only known columns.
    existing_cols = {
        r[1] for r in conn.execute(
            "PRAGMA table_info(listing_duplicate_candidates)"
        ).fetchall()
    }

    # All columns in the new schema (from _DDL); we copy the intersection.
    new_cols = [
        "id", "listing_id_a", "listing_id_b", "score", "classification",
        "evidence", "differences", "status", "last_evaluated_at",
        "operator_comment", "reviewed_at", "created_at", "updated_at",
    ]
    copy_cols = [c for c in new_cols if c in existing_cols]
    col_list = ", ".join(copy_cols)

    conn.execute("ALTER TABLE listing_duplicate_candidates RENAME TO _ldc_old")

    # Create fresh table with new schema (DDL already split above; we re-run
    # just the CREATE TABLE statement).
    create_stmt = _DDL.strip().split(";")[0].strip()
    conn.execute(create_stmt)

    # Copy all rows from old table; columns absent in old schema default to NULL.
    conn.execute(f"INSERT INTO listing_duplicate_candidates ({col_list}) SELECT {col_list} FROM _ldc_old")

    conn.execute("DROP TABLE _ldc_old")

    # Recreate indexes (IF NOT EXISTS makes this a no-op when already present).
    for stmt in _DDL.strip().split(";")[1:]:
        stmt = stmt.strip()
        if stmt:
            conn.execute(stmt)


def upsert_candidate(
    conn,
    lid_a: int,
    lid_b: int,
    result: dict[str, Any],
    *,
    run_ts: str,
) -> None:
    """
    Insert or update a candidate row.  Existing operator status is preserved
    on update.  Stable ordering: lid_a < lid_b always.

    run_ts is the ISO timestamp of the current detection run, stored in
    last_evaluated_at so stale detection can identify rows not seen in
    a subsequent run.
    """
    a, b = min(lid_a, lid_b), max(lid_a, lid_b)
    now = datetime.now().isoformat()
    evidence = json.dumps(result["reasons"])
    differences = json.dumps(result["differences"])
    score = result["score"]
    classification = result["classification"]

    existing = conn.execute(
        "SELECT id, status FROM listing_duplicate_candidates WHERE listing_id_a=? AND listing_id_b=?",
        (a, b),
    ).fetchone()

    if existing:
        # Preserve operator status; update scoring and mark as evaluated
        conn.execute(
            """
            UPDATE listing_duplicate_candidates
            SET score=?, classification=?, evidence=?, differences=?,
                last_evaluated_at=?, updated_at=?,
                status = CASE
                    WHEN status = 'STALE' THEN 'OPEN'
                    ELSE status
                END
            WHERE listing_id_a=? AND listing_id_b=?
            """,
            (score, classification, evidence, differences, run_ts, now, a, b),
        )
    else:
        conn.execute(
            """
            INSERT INTO listing_duplicate_candidates
            (listing_id_a, listing_id_b, score, classification, evidence, differences,
             status, last_evaluated_at, created_at, updated_at)
            VALUES (?,?,?,?,?,?,'OPEN',?,?,?)
            """,
            (a, b, score, classification, evidence, differences, run_ts, now, now),
        )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run_detection(*, dry_run: bool = False, conn=None) -> dict[str, Any]:
    """
    Run the full detection pipeline.

    dry_run=True: score candidates but do not write to the database.

    Returns summary counts by classification and a list of top candidates.
    """
    should_close = conn is None
    conn = conn or database.get_connection()

    try:
        ensure_schema(conn)
        pairs = generate_candidates(conn)
        run_ts = datetime.now().isoformat()
        evaluated_pairs: set[tuple[int, int]] = set()

        results: list[dict] = []
        for a_data, b_data in pairs:
            result = score_pair(a_data, b_data)
            result["listing_id_a"] = a_data["id"]
            result["listing_id_b"] = b_data["id"]
            result["source_listing_id_a"] = a_data["source_listing_id"]
            result["source_listing_id_b"] = b_data["source_listing_id"]
            results.append(result)

            if not dry_run:
                upsert_candidate(conn, a_data["id"], b_data["id"], result, run_ts=run_ts)
                pair_key = (min(a_data["id"], b_data["id"]), max(a_data["id"], b_data["id"]))
                evaluated_pairs.add(pair_key)

        if not dry_run:
            # Mark OPEN pairs not seen in this run as STALE.
            # Preserves CONFIRMED_SAME / CONFIRMED_DIFFERENT / DISMISSED.
            if evaluated_pairs:
                placeholders = ",".join("(?,?)" for _ in evaluated_pairs)
                params: list = []
                for pa, pb in evaluated_pairs:
                    params.extend([pa, pb])
                conn.execute(
                    f"""
                    UPDATE listing_duplicate_candidates
                    SET status = 'STALE', updated_at = ?
                    WHERE status = 'OPEN'
                      AND (listing_id_a, listing_id_b) NOT IN ({placeholders})
                    """,
                    [run_ts] + params,
                )
            else:
                # No candidates at all — mark every OPEN row stale
                conn.execute(
                    "UPDATE listing_duplicate_candidates SET status='STALE', updated_at=? WHERE status='OPEN'",
                    (run_ts,),
                )
            conn.commit()

        by_class: dict[str, int] = {}
        for r in results:
            by_class[r["classification"]] = by_class.get(r["classification"], 0) + 1

        top_10 = sorted(results, key=lambda x: x["score"], reverse=True)[:10]

        return {
            "total_candidates": len(results),
            "by_classification": by_class,
            "top_candidates": top_10,
        }

    finally:
        if should_close:
            conn.close()


def score_listing_pair(listing_id_a: int, listing_id_b: int, *, conn=None) -> dict[str, Any]:
    """Score a single explicit listing pair and return the result dict."""
    should_close = conn is None
    conn = conn or database.get_connection()
    try:
        def _fetch(lid):
            row = conn.execute(
                "SELECT id, source_id, source_listing_id, current_price, current_mileage, "
                "current_seller, current_description, current_options FROM listings WHERE id=?",
                (lid,),
            ).fetchone()
            if row is None:
                raise ValueError(f"listing {lid} not found")
            snap = _get_snapshot_fields(lid, conn)
            return _listing_data(row, snap)

        a_data = _fetch(listing_id_a)
        b_data = _fetch(listing_id_b)
        return score_pair(a_data, b_data)
    finally:
        if should_close:
            conn.close()


# ---------------------------------------------------------------------------
# Portal DB helpers
# ---------------------------------------------------------------------------

# Status values that represent operator review decisions
REVIEWED_STATUSES = {"CONFIRMED_SAME", "CONFIRMED_DIFFERENT", "UNSURE", "DISMISSED"}
# Status values that belong in the active review queue
REVIEWABLE_STATUSES = {"OPEN", "STALE"}
# Classifications shown by default in the review queue (LOW excluded)
DEFAULT_CLASSIFICATIONS = {"VERY_STRONG", "STRONG", "POSSIBLE"}


def _listing_detail(listing_id: int, conn) -> dict[str, Any]:
    """Return a display dict for a single listing including source metadata."""
    row = conn.execute(
        """
        SELECT l.id, l.source_id, s.display_name, l.source_listing_id,
               l.current_price, l.current_mileage, l.current_seller,
               l.current_description, l.current_options,
               sl.source_url
        FROM listings l
        JOIN sources s ON s.id = l.source_id
        JOIN source_listings sl ON sl.id = l.source_listing_row_id
        WHERE l.id = ?
        """,
        (listing_id,),
    ).fetchone()
    if row is None:
        return {}
    lid, source_id, source_label, source_listing_id, price, mileage, seller, desc, options, url = row
    snap = _get_snapshot_fields(lid, conn)
    return {
        "id": lid,
        "source_id": source_id,
        "source_label": source_label or f"Source {source_id}",
        "source_listing_id": source_listing_id,
        "source_url": url,
        "price": price,
        "mileage": mileage,
        "seller": seller,
        "description": desc,
        "title": snap.get("title"),
        "year": snap.get("year") or (snap.get("first_registration") or "")[:4] or None,
        "first_registration": snap.get("first_registration"),
        "colour": snap.get("colour") or snap.get("color"),
        "power_hp": snap.get("power_hp") or snap.get("hp"),
        "drivetrain": snap.get("drivetrain") or snap.get("drive"),
        "transmission": snap.get("transmission") or snap.get("gearbox"),
        "vin": snap.get("vin"),
    }


def get_duplicate_candidates(
    *,
    classification: str | None = None,
    status: str | None = None,
    conn=None,
) -> list[dict[str, Any]]:
    """
    Return candidate rows for the review portal.

    classification: one of VERY_STRONG/STRONG/POSSIBLE/LOW, or None for all
                    reviewable (excludes LOW by default when None).
    status:         specific status filter, or None for OPEN only.
    """
    should_close = conn is None
    conn = conn or database.get_connection()
    try:
        ensure_schema(conn)
        conn.commit()

        clauses = []
        params: list = []

        if classification:
            clauses.append("ldc.classification = ?")
            params.append(classification)
        else:
            # Default: exclude LOW
            placeholders = ",".join("?" for _ in DEFAULT_CLASSIFICATIONS)
            clauses.append(f"ldc.classification IN ({placeholders})")
            params.extend(sorted(DEFAULT_CLASSIFICATIONS))

        if status:
            clauses.append("ldc.status = ?")
            params.append(status)
        else:
            clauses.append("ldc.status = 'OPEN'")

        where = "WHERE " + " AND ".join(clauses) if clauses else ""

        rows = conn.execute(
            f"""
            SELECT ldc.id, ldc.listing_id_a, ldc.listing_id_b,
                   ldc.score, ldc.classification, ldc.evidence, ldc.differences,
                   ldc.status, ldc.operator_comment, ldc.reviewed_at, ldc.updated_at
            FROM listing_duplicate_candidates ldc
            {where}
            ORDER BY
                CASE ldc.classification
                    WHEN 'VERY_STRONG' THEN 1
                    WHEN 'STRONG'      THEN 2
                    WHEN 'POSSIBLE'    THEN 3
                    ELSE 4
                END,
                ldc.score DESC
            """,
            params,
        ).fetchall()

        return [_row_to_candidate(r) for r in rows]
    finally:
        if should_close:
            conn.close()


def get_duplicate_candidate(candidate_id: int, *, conn=None) -> dict[str, Any] | None:
    """Return a single candidate with full listing details for the detail/review page."""
    should_close = conn is None
    conn = conn or database.get_connection()
    try:
        ensure_schema(conn)
        conn.commit()

        row = conn.execute(
            """
            SELECT ldc.id, ldc.listing_id_a, ldc.listing_id_b,
                   ldc.score, ldc.classification, ldc.evidence, ldc.differences,
                   ldc.status, ldc.operator_comment, ldc.reviewed_at, ldc.updated_at
            FROM listing_duplicate_candidates ldc
            WHERE ldc.id = ?
            """,
            (candidate_id,),
        ).fetchone()
        if row is None:
            return None
        candidate = _row_to_candidate(row)
        candidate["listing_a"] = _listing_detail(candidate["listing_id_a"], conn)
        candidate["listing_b"] = _listing_detail(candidate["listing_id_b"], conn)
        return candidate
    finally:
        if should_close:
            conn.close()


def get_next_open_candidate(after_id: int | None = None, *, conn=None) -> int | None:
    """Return the id of the next OPEN VERY_STRONG/STRONG/POSSIBLE candidate.

    If after_id is given, returns the next one after that candidate (by sort
    order).  Returns None when the queue is empty.
    """
    should_close = conn is None
    conn = conn or database.get_connection()
    try:
        ensure_schema(conn)
        conn.commit()

        order_expr = """
            CASE classification
                WHEN 'VERY_STRONG' THEN 1
                WHEN 'STRONG'      THEN 2
                WHEN 'POSSIBLE'    THEN 3
                ELSE 4
            END, score DESC, id ASC
        """
        placeholders = ",".join("?" for _ in DEFAULT_CLASSIFICATIONS)
        base_where = f"status = 'OPEN' AND classification IN ({placeholders})"
        base_params = list(sorted(DEFAULT_CLASSIFICATIONS))

        if after_id is not None:
            # Fetch current row's sort key to find what comes after it
            cur = conn.execute(
                "SELECT classification, score, id FROM listing_duplicate_candidates WHERE id=?",
                (after_id,),
            ).fetchone()
            if cur:
                cls_map = {"VERY_STRONG": 1, "STRONG": 2, "POSSIBLE": 3}
                cur_rank = cls_map.get(cur[0], 4)
                cur_score = cur[1]
                cur_id = cur[2]
                row = conn.execute(
                    f"""
                    SELECT id FROM listing_duplicate_candidates
                    WHERE {base_where}
                      AND (
                        CASE classification WHEN 'VERY_STRONG' THEN 1 WHEN 'STRONG' THEN 2
                             WHEN 'POSSIBLE' THEN 3 ELSE 4 END > ?
                        OR (CASE classification WHEN 'VERY_STRONG' THEN 1 WHEN 'STRONG' THEN 2
                             WHEN 'POSSIBLE' THEN 3 ELSE 4 END = ? AND score < ?)
                        OR (CASE classification WHEN 'VERY_STRONG' THEN 1 WHEN 'STRONG' THEN 2
                             WHEN 'POSSIBLE' THEN 3 ELSE 4 END = ? AND score = ? AND id > ?)
                      )
                    ORDER BY {order_expr}
                    LIMIT 1
                    """,
                    base_params + [cur_rank, cur_rank, cur_score, cur_rank, cur_score, cur_id],
                ).fetchone()
                # Return the next candidate, or None if after_id was the last one.
                # Never wrap around to the first candidate when after_id is specified.
                return row[0] if row else None

        # No after_id: return the first OPEN candidate in sort order.
        row = conn.execute(
            f"SELECT id FROM listing_duplicate_candidates WHERE {base_where} ORDER BY {order_expr} LIMIT 1",
            base_params,
        ).fetchone()
        return row[0] if row else None
    finally:
        if should_close:
            conn.close()


def update_duplicate_candidate_review(
    candidate_id: int,
    *,
    status: str,
    operator_comment: str | None = None,
    conn=None,
) -> None:
    """
    Persist an operator review decision.

    SAFETY CONTRACT:
    - Only listing_duplicate_candidates is modified.
    - listings.vehicle_id is never touched.
    - No Vehicle is created or merged.
    - CONFIRMED_SAME means "human believes same physical vehicle" — not an
      automatic vehicle merge.  Vehicle resolution remains a separate step.
    """
    valid = {"CONFIRMED_SAME", "CONFIRMED_DIFFERENT", "UNSURE", "DISMISSED", "OPEN"}
    if status not in valid:
        raise ValueError(f"Invalid review status: {status!r}")
    should_close = conn is None
    conn = conn or database.get_connection()
    try:
        now = datetime.now().isoformat()
        conn.execute(
            """
            UPDATE listing_duplicate_candidates
            SET status=?, operator_comment=?, reviewed_at=?, updated_at=?
            WHERE id=?
            """,
            (status, operator_comment or None, now, now, candidate_id),
        )
        conn.commit()
    finally:
        if should_close:
            conn.close()


def get_review_summary(*, conn=None) -> dict[str, int]:
    """Return counts by status for the review progress summary."""
    should_close = conn is None
    conn = conn or database.get_connection()
    try:
        ensure_schema(conn)
        conn.commit()
        rows = conn.execute(
            """
            SELECT status, COUNT(*) FROM listing_duplicate_candidates
            WHERE classification IN ('VERY_STRONG','STRONG','POSSIBLE')
            GROUP BY status
            """
        ).fetchall()
        return {r[0]: r[1] for r in rows}
    finally:
        if should_close:
            conn.close()


def _row_to_candidate(row) -> dict[str, Any]:
    cid, lid_a, lid_b, score, classification, evidence_json, diff_json, status, comment, reviewed_at, updated_at = row
    try:
        evidence = json.loads(evidence_json) if evidence_json else []
    except (ValueError, TypeError):
        evidence = []
    try:
        differences = json.loads(diff_json) if diff_json else []
    except (ValueError, TypeError):
        differences = []
    return {
        "id": cid,
        "listing_id_a": lid_a,
        "listing_id_b": lid_b,
        "score": score,
        "classification": classification,
        "evidence": evidence,
        "differences": differences,
        "status": status,
        "operator_comment": comment,
        "reviewed_at": reviewed_at,
        "updated_at": updated_at,
    }
